name: Deploy Todo List App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t todo-list-app .

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com

      - name: Push Docker image to ECR
        run: |
          docker tag todo-list-app:latest <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/todo-list-app:latest
          docker push <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/todo-list-app:latest

      - name: Deploy to EC2 (or ECS)
        run: |
          ssh -i "your-key.pem" ec2-user@your-ec2-ip "docker pull <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/todo-list-app:latest && docker run -d -p 80:80 todo-list-app"
